// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NuevoProveedorGastos")]
    public partial class NuevoProveedorGastosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "NuevoProveedorGastos", "  Validar el registro de un nuevo proveedor desde el módulo de Gasto", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NuevoProveedorGastos.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
  #line hidden
#line 5
    await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://161.132.67.82:31097/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
    await testRunner.AndAsync("accede al módulo \'Gasto\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync("accede al submódulo \'Ver\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario hace clic en el botón \'Nuevo Gasto\' en Gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Abrir el formulario de registro de proveedor desde Nuevo Gasto")]
        [NUnit.Framework.CategoryAttribute("AbrirFormularioProveedor")]
        public async System.Threading.Tasks.Task AbrirElFormularioDeRegistroDeProveedorDesdeNuevoGasto()
        {
            string[] tagsOfScenario = new string[] {
                    "AbrirFormularioProveedor"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Abrir el formulario de registro de proveedor desde Nuevo Gasto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.WhenAsync("el usuario hace clic en el botón \'+\' para registrar un nuevo proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("se muestra el formulario \'REGISTRO DE PROVEEDOR\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verificar mensajes de error por campos vacíos")]
        [NUnit.Framework.CategoryAttribute("ValidacionesProveedor")]
        public async System.Threading.Tasks.Task VerificarMensajesDeErrorPorCamposVacios()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionesProveedor"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar mensajes de error por campos vacíos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.WhenAsync("el usuario abre el formulario de registro de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.AndAsync("deja todos los campos obligatorios vacíos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("guarda el proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.ThenAsync("el sistema muestra mensaje de validación para cada campo obligatorio", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar formatos incorrectos en los campos de documento y correo")]
        [NUnit.Framework.CategoryAttribute("ValidacionFormatos")]
        public async System.Threading.Tasks.Task ValidarFormatosIncorrectosEnLosCamposDeDocumentoYCorreo()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionFormatos"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar formatos incorrectos en los campos de documento y correo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.WhenAsync("el usuario abre el formulario de registro de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "TipoDocumento",
                            "DOC. NACIONAL DE IDENTIDAD"});
                table2.AddRow(new string[] {
                            "NroDocumento",
                            "ABC123"});
                table2.AddRow(new string[] {
                            "Email",
                            "correo_invalido"});
#line 32
    await testRunner.AndAsync("ingresa datos con formatos inválidos:", ((string)(null)), table2, "And ");
#line hidden
#line 36
    await testRunner.AndAsync("guarda el proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.ThenAsync("el sistema muestra mensajes de error de formato", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar un nuevo proveedor con todos los datos válidos")]
        [NUnit.Framework.CategoryAttribute("RegistroProveedorValido")]
        public async System.Threading.Tasks.Task RegistrarUnNuevoProveedorConTodosLosDatosValidos()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroProveedorValido"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar un nuevo proveedor con todos los datos válidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 43
    await testRunner.WhenAsync("el usuario abre el formulario de registro de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "TipoDocumento",
                            "DOC. NACIONAL DE IDENTIDAD"});
                table3.AddRow(new string[] {
                            "NroDocumento",
                            "25658498"});
                table3.AddRow(new string[] {
                            "ApellidoPaterno",
                            "JAPA"});
                table3.AddRow(new string[] {
                            "ApellidoMaterno",
                            "ARQUENO"});
                table3.AddRow(new string[] {
                            "Nombres",
                            "SARAI YOLANDA"});
                table3.AddRow(new string[] {
                            "Nacionalidad",
                            "PERÚ"});
                table3.AddRow(new string[] {
                            "FechaNacimiento",
                            "09/11/1990"});
                table3.AddRow(new string[] {
                            "Sexo",
                            "FEMENINO"});
                table3.AddRow(new string[] {
                            "EstadoCivil",
                            "SOLTERO(A)"});
                table3.AddRow(new string[] {
                            "Email",
                            "saraijp8@gmail.com"});
                table3.AddRow(new string[] {
                            "Telefono",
                            "999888777"});
                table3.AddRow(new string[] {
                            "Pais",
                            "PERÚ"});
                table3.AddRow(new string[] {
                            "Ubigeo",
                            "HUANUCO - LEONCIO PRADO - RUPA RUPA"});
                table3.AddRow(new string[] {
                            "Detalles",
                            "JR. SAN MARTÍN 123"});
#line 44
    await testRunner.AndAsync("completa el formulario de proveedor con los siguientes datos:", ((string)(null)), table3, "And ");
#line hidden
#line 59
    await testRunner.AndAsync("guarda el proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.ThenAsync("el sistema muestra mensaje de confirmación de registro exitoso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar formato de teléfono con caracteres especiales")]
        [NUnit.Framework.CategoryAttribute("ValidacionTelefono")]
        public async System.Threading.Tasks.Task ValidarFormatoDeTelefonoConCaracteresEspeciales()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionTelefono"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar formato de teléfono con caracteres especiales", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
  await testRunner.WhenAsync("el usuario abre el formulario de registro de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "TipoDocumento",
                            "DOC. NACIONAL DE IDENTIDAD"});
                table4.AddRow(new string[] {
                            "NroDocumento",
                            "45440133"});
                table4.AddRow(new string[] {
                            "ApellidoPaterno",
                            "JAPA"});
                table4.AddRow(new string[] {
                            "ApellidoMaterno",
                            "MOLINA"});
                table4.AddRow(new string[] {
                            "Nombres",
                            "JHON"});
                table4.AddRow(new string[] {
                            "Nacionalidad",
                            "PERÚ"});
                table4.AddRow(new string[] {
                            "FechaNacimiento",
                            "09/11/1990"});
                table4.AddRow(new string[] {
                            "Sexo",
                            "MASCULINO"});
                table4.AddRow(new string[] {
                            "EstadoCivil",
                            "CASADO"});
                table4.AddRow(new string[] {
                            "Email",
                            "molinahjhon@gmail.com"});
                table4.AddRow(new string[] {
                            "Telefono",
                            "#####SSFF"});
                table4.AddRow(new string[] {
                            "Pais",
                            "PERÚ"});
                table4.AddRow(new string[] {
                            "Ubigeo",
                            "HUANUCO - LEONCIO PRADO - RUPA RUPA"});
                table4.AddRow(new string[] {
                            "Detalles",
                            "JR. SAN MARTÍN 123"});
#line 65
  await testRunner.AndAsync("completa el formulario de proveedor con los siguientes datos:", ((string)(null)), table4, "And ");
#line hidden
#line 80
  await testRunner.AndAsync("guarda el proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
  await testRunner.ThenAsync("el sistema permite guardar el registro o muestra advertencia informativa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar que el sistema acepte diferentes dominios de correo electrónico")]
        [NUnit.Framework.CategoryAttribute("ValidacionCorreos")]
        [NUnit.Framework.TestCaseAttribute("sarajapa8@hotmail.com", null)]
        [NUnit.Framework.TestCaseAttribute("sarajapa8@outlook.com", null)]
        [NUnit.Framework.TestCaseAttribute("sarajapa8@l.hotmail.com", null)]
        [NUnit.Framework.TestCaseAttribute("sarajapa8@gmail.com", null)]
        [NUnit.Framework.TestCaseAttribute("sarajapa8@yahoo.es", null)]
        public async System.Threading.Tasks.Task ValidarQueElSistemaAcepteDiferentesDominiosDeCorreoElectronico(string correo, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ValidacionCorreos"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Correo", correo);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar que el sistema acepte diferentes dominios de correo electrónico", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 88
    await testRunner.WhenAsync("el usuario abre el formulario de registro de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "TipoDocumento",
                            "DOC. NACIONAL DE IDENTIDAD"});
                table5.AddRow(new string[] {
                            "NroDocumento",
                            "73582270"});
                table5.AddRow(new string[] {
                            "Email",
                            "sarajapa8@outlook.com"});
                table5.AddRow(new string[] {
                            "ApellidoPaterno",
                            "JAPA"});
                table5.AddRow(new string[] {
                            "ApellidoMaterno",
                            "ARQUEÑO"});
                table5.AddRow(new string[] {
                            "Nombres",
                            "SARAI YOLANDA"});
#line 89
    await testRunner.AndAsync("ingresa los siguientes datos mínimos:", ((string)(null)), table5, "And ");
#line hidden
#line 96
    await testRunner.AndAsync("guarda el proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
    await testRunner.ThenAsync("el sistema permite guardar el registro correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar que tras ingresar el número de documento y presionar ENTER se puedan edit" +
            "ar otros campos")]
        [NUnit.Framework.CategoryAttribute("ValidacionEnterDocumento")]
        public async System.Threading.Tasks.Task ValidarQueTrasIngresarElNumeroDeDocumentoYPresionarENTERSePuedanEditarOtrosCampos()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionEnterDocumento"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar que tras ingresar el número de documento y presionar ENTER se puedan edit" +
                    "ar otros campos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 111
  await testRunner.WhenAsync("el usuario abre el formulario de registro de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "TipoDocumento",
                            "DOC. NACIONAL DE IDENTIDAD"});
                table6.AddRow(new string[] {
                            "NroDocumento",
                            "73582270"});
#line 112
  await testRunner.AndAsync("completa el formulario de proveedor con los siguientes datos:", ((string)(null)), table6, "And ");
#line hidden
#line 115
  await testRunner.AndAsync("presiona la tecla ENTER después de ingresar el número de documento", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
  await testRunner.ThenAsync("el sistema muestra que los demás campos siguen habilitados para edición", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
