// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RegistrarNuevoGasto")]
    public partial class RegistrarNuevoGastoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "RegistrarNuevoGasto", "  Validar el registro de un nuevo gasto en el módulo Gasto", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "RegistrarNuevoGasto.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
  #line hidden
#line 5
    await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://161.132.67.82:31097/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
    await testRunner.AndAsync("accede al módulo \'Gasto\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync("accede al submódulo \'Ver\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario hace clic en el botón \'Nuevo Gasto\' en Gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar un nuevo gasto con datos válidos")]
        [NUnit.Framework.CategoryAttribute("RegistrarNuevoGasto")]
        public async System.Threading.Tasks.Task RegistrarUnNuevoGastoConDatosValidos()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistrarNuevoGasto"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar un nuevo gasto con datos válidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            "73582270"});
                table8.AddRow(new string[] {
                            "Concepto",
                            "MANTENIMIENTO"});
                table8.AddRow(new string[] {
                            "Detalle",
                            "Compra de repuestos de oficina"});
                table8.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table8.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table8.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table8.AddRow(new string[] {
                            "Importe",
                            "250.00"});
                table8.AddRow(new string[] {
                            "IGV",
                            "GASTO CON IGV"});
#line 15
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table8, "When ");
#line hidden
#line 24
    await testRunner.AndAsync("guarda el gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.ThenAsync("el sistema muestra mensaje de confirmación o inconsistencia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar mensaje cuando el importe es 0")]
        [NUnit.Framework.CategoryAttribute("ValidacionImporteCero")]
        public async System.Threading.Tasks.Task ValidarMensajeCuandoElImporteEs0()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionImporteCero"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar mensaje cuando el importe es 0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            "73582270"});
                table9.AddRow(new string[] {
                            "Concepto",
                            "MANTENIMIENTO"});
                table9.AddRow(new string[] {
                            "Detalle",
                            "Compra de útiles de oficina"});
                table9.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table9.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table9.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table9.AddRow(new string[] {
                            "Importe",
                            "0.00"});
                table9.AddRow(new string[] {
                            "IGV",
                            "GASTO CON IGV"});
#line 32
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table9, "When ");
#line hidden
#line 41
    await testRunner.AndAsync("guarda el gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.ThenAsync("el sistema muestra mensaje de inconsistencia con texto \"Es necesario que el impor" +
                        "te sea mayor a 0.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar mensaje cuando el total es 0")]
        [NUnit.Framework.CategoryAttribute("ValidacionTotalCero")]
        public async System.Threading.Tasks.Task ValidarMensajeCuandoElTotalEs0()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionTotalCero"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar mensaje cuando el total es 0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            "73582270"});
                table10.AddRow(new string[] {
                            "Concepto",
                            "MANTENIMIENTO"});
                table10.AddRow(new string[] {
                            "Detalle",
                            "Compra de útiles"});
                table10.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table10.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table10.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table10.AddRow(new string[] {
                            "Importe",
                            "0.00"});
                table10.AddRow(new string[] {
                            "IGV",
                            "GASTO CON IGV"});
#line 49
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table10, "When ");
#line hidden
#line 58
    await testRunner.AndAsync("guarda el gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.ThenAsync("el sistema muestra mensaje de inconsistencia con texto \"Es necesario que el total" +
                        " sea mayor a 0.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar mensajes múltiples cuando se dejan varios campos vacíos o en 0")]
        [NUnit.Framework.CategoryAttribute("ValidacionCamposObligatorios")]
        public async System.Threading.Tasks.Task ValidarMensajesMultiplesCuandoSeDejanVariosCamposVaciosOEn0()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionCamposObligatorios"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar mensajes múltiples cuando se dejan varios campos vacíos o en 0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            ""});
                table11.AddRow(new string[] {
                            "Concepto",
                            ""});
                table11.AddRow(new string[] {
                            "Detalle",
                            ""});
                table11.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table11.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table11.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table11.AddRow(new string[] {
                            "Importe",
                            "800.00"});
                table11.AddRow(new string[] {
                            "IGV",
                            "SIN IGV"});
#line 66
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table11, "When ");
#line hidden
#line 75
    await testRunner.AndAsync("guarda el gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.ThenAsync("el sistema muestra mensaje de inconsistencia con texto \"Es necesario seleccionar " +
                        "un concepto para el gasto.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
    await testRunner.AndAsync("el sistema muestra mensaje de inconsistencia con texto \"Es necesario que el impor" +
                        "te sea mayor a 0.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("el sistema muestra mensaje de inconsistencia con texto \"Es necesario que el total" +
                        " sea mayor a 0.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar comportamiento cuando el importe es excesivamente alto")]
        [NUnit.Framework.CategoryAttribute("ValidacionImporteExcesivo")]
        public async System.Threading.Tasks.Task ValidarComportamientoCuandoElImporteEsExcesivamenteAlto()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacionImporteExcesivo"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar comportamiento cuando el importe es excesivamente alto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            "73582270"});
                table12.AddRow(new string[] {
                            "Concepto",
                            "MANTENIMIENTO"});
                table12.AddRow(new string[] {
                            "Detalle",
                            "Validar cálculo por valor extremo"});
                table12.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table12.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table12.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table12.AddRow(new string[] {
                            "Importe",
                            "9999999999999999999999999999999999999999"});
                table12.AddRow(new string[] {
                            "IGV",
                            "GASTO CON IGV"});
#line 85
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table12, "When ");
#line hidden
#line 94
    await testRunner.AndAsync("guarda el gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
    await testRunner.ThenAsync("el sistema muestra mensaje de inconsistencia con texto \"El importe excede el valo" +
                        "r permitido o genera desbordamiento en el cálculo.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar un gasto con la opción \'Al Crédito\' en modo Rápido")]
        [NUnit.Framework.CategoryAttribute("GastoCreditoRapido")]
        public async System.Threading.Tasks.Task RegistrarUnGastoConLaOpcionAlCreditoEnModoRapido()
        {
            string[] tagsOfScenario = new string[] {
                    "GastoCreditoRapido"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar un gasto con la opción \'Al Crédito\' en modo Rápido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            "73582270"});
                table13.AddRow(new string[] {
                            "Concepto",
                            "MANTENIMIENTO"});
                table13.AddRow(new string[] {
                            "Detalle",
                            "Compra a crédito en modo rápido"});
                table13.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table13.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table13.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table13.AddRow(new string[] {
                            "Importe",
                            "1000.00"});
                table13.AddRow(new string[] {
                            "IGV",
                            "GASTO CON IGV"});
#line 102
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table13, "When ");
#line hidden
#line 111
    await testRunner.AndAsync("selecciona la opción \"AL CRÉDITO\" con modo \"Rápido\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
    await testRunner.AndAsync("guarda el gasto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
    await testRunner.ThenAsync("el sistema muestra mensaje de confirmación o inconsistencia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar un gasto con la opción \'Al Crédito\' en modo Configurar")]
        [NUnit.Framework.CategoryAttribute("GastoCreditoConfigurar")]
        public async System.Threading.Tasks.Task RegistrarUnGastoConLaOpcionAlCreditoEnModoConfigurar()
        {
            string[] tagsOfScenario = new string[] {
                    "GastoCreditoConfigurar"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar un gasto con la opción \'Al Crédito\' en modo Configurar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Proveedor",
                            "73582270"});
                table14.AddRow(new string[] {
                            "Concepto",
                            "MANTENIMIENTO"});
                table14.AddRow(new string[] {
                            "Detalle",
                            "Compra a crédito configurada"});
                table14.AddRow(new string[] {
                            "Documento",
                            "NOTA DE GASTO (INTERNA)"});
                table14.AddRow(new string[] {
                            "Fecha",
                            "09/11/2025"});
                table14.AddRow(new string[] {
                            "Observacion",
                            "Ninguna"});
                table14.AddRow(new string[] {
                            "Importe",
                            "220000"});
                table14.AddRow(new string[] {
                            "IGV",
                            "GASTO CON IGV"});
#line 120
    await testRunner.WhenAsync("el usuario completa el formulario de registro de gasto:", ((string)(null)), table14, "When ");
#line hidden
#line 129
    await testRunner.AndAsync("selecciona la opción \"AL CRÉDITO\" con modo \"Configurar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Inicial",
                            "200"});
                table15.AddRow(new string[] {
                            "DiaPago",
                            "09/11/2025"});
#line 130
    await testRunner.AndAsync("completa la configuración de crédito con los siguientes datos:", ((string)(null)), table15, "And ");
#line hidden
#line 133
    await testRunner.AndAsync("confirma el financiamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.ThenAsync("el sistema muestra mensaje de inconsistencia con texto \"Es necesario seleccionar " +
                        "un concepto para el gasto.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
